### ISSUE TITLE
Entire image not showing when using addon (Mojave OS) 

### ISSUE THREAD

**Issue by padenw24** [glutanimate/popup-dictionary#17]
#### Problem description

Hi, recently got a new mac and noticed that when searching for a word using the addon, the entire picture in the searched cards does not show up. It seems like it may be about half of the image shows up? Not sure if there is an easy work around for this issue? I am using the current version of anki and the most up to date version of the addon. 

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've restarted Anki to see if it helps
 - [ x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x ] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up
Font: {{cloze:Text}}

Styling: .card {
 font-family: Times New Roman;
 font-size: 24px;
 text-align: center;
 color: black;
 background-color: lavender;
}

Back template: 
{{cloze:Text}}
<br>
<div style="font-style:italic;color:Navy;">

{{Extra}}</div>

##### If you are using Anki 2.1

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
Anki 2.1.14 (7b93e985) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Mac 10.14.5
Flags: frz=True ao=True sv=1

Add-ons:

Speed Focus Mode auto-alert auto-reveal auto-fail
ImageResizer
Pop-up Dictionary beta
Hierarchical Tags Addon 20  21
```

#####  If you are using Anki 2.0

*Please open Anki, go to Help → About, find the two lines starting with `Version:` and `Qt`, and copy-paste them between the backticks below:*

```

```

*Please fill in details about your operating system (Windows/macOS/Linux, which version):*

- OS:
- version:

*Please open Anki, go to Tools → Add-ons, take a screenshot of your installed add-ons, and paste it below:*

BUG: 
![image](https://user-images.githubusercontent.com/53122080/61581615-bd841880-aaee-11e9-92ee-cb0f014b8c89.png)

*If you've received an error message, please copy and paste it between the backticks below:*

```python

```

**Comment by glutanimate** [comment]
Hi. Thanks for the report. Would you mind posting a screenshot of the bug in action? Also, it would be very helpful if you could copy and paste the the content of the front template, styling, and back template field for the affected card (Head to Edit (e) → Click on Cards → Copy/paste the content of the 3 aforementioned fields on the left side of the window here).

**Comment by glutanimate** [comment]
I would also appreciate it if you could edit your bug report to fill out the section "Information about your Anki set-up". There's not much I can do at the moment since I don't know anything about your particular set-up.

**Comment by padenw24** [comment]
Thanks man! Added the info you needed, let me know if there is anything else. Thanks for all you've done.

**Comment by glutanimate** [comment]
Thanks for taking the time to add the info, @padenw24 !

It seems like this is the result of a change introduced with the latest Anki update (https://github.com/dae/anki/commit/47478e584f34131a3b22a1beebb03d2ca7dbf83d). I will look into pushing a fix for this soon, but for the time being you could add the following snippet to the 'Styling' section of your card templates:

```css
.qtip img {
   max-width: 95% !important;
   max-height: 95% !important;
}
```

That should adjust the image size to fit into the pop-up again.
