### ISSUE TITLE
Popup window not wide enough (or need horizontal scroll)

### ISSUE THREAD

**Issue by bradydjohnson** [glutanimate/popup-dictionary#29]
#### Problem description

The popup window is not wide enough to see many images that I have on the backs of my cards. See below.
![image](https://user-images.githubusercontent.com/6741590/73013726-7567ea80-3dde-11ea-9c0f-e2cbd2aef282.png)

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ x] I've restarted Anki to see if it helps
 - [ x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [ ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

Version 2.1.19 (3c8690ae)

##### If you are using Anki 2.1

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
Anki 2.1.19 (3c8690ae) Python 3.8.0 Qt 5.14.0 PyQt 5.13.2
Platform: Mac 10.15.2
Flags: frz=True ao=True sv=2

Add-ons:

Edit Field During Review (disabled)
Speed Focus Mode auto-alert auto-reveal auto-fail
Special Fields
Pretzel Logic Retention Benchmarking (disabled)
Image Occlusion Enhanced for Anki 21 alpha
Search and Replace Tags (disabled)
load balancer (disabled)
Symbols
Night Mode
Pop-up Dictionary beta
More Decks Stats and Time Left (disabled)
Hint Hotkeys
Study Logger (disabled)
Customize Sidebar
Load Balanced Scheduler
Card Info During Review
Customize Keyboard Shortcuts
Button Colours Good Again
ReMemorize Rescheduler with sibling and logging v121 (disabled)
Clickable Tags v10
Ankidown - The advanced importer for Anki (disabled)
Frozen Fields
Blitzkrieg II - Advanced Browser Sidebar BETA5 (disabled)
Pokemanki for both Anki 20 and 21 (disabled)
Syllabus - Anki Statistics and Export by Tag and Deck
More Overview Stats 21 (disabled)
Echelon - Improved Hierarchical Tags for Anki 21 (disabled)
Slackers Delight PostponeDefer Button (disabled)
Free_Weekend_Load_Balancer-master (disabled)
BetterTags
Cloze Overlapper
Review Heatmap
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python

```

**Comment by glutanimate** [comment]
Thanks for the report, Brady! This should be fixed with the next release of the add-on (a67736b611a5cedd2aa30e9e61a27722586b9bf0. For an interim solution until the release is out, please see here: https://github.com/glutanimate/popup-dictionary/issues/17#issuecomment-514750106
