### ISSUE TITLE
Highlighting not working

### ISSUE THREAD

**Issue by zankidemon** [glutanimate/popup-dictionary#3]
## Prerequisite checklist

* [X ] In case of a bug: Have you tried restarting Anki?
* [X ] Are you running the latest version of the add-on. Have you redownloaded the add-on from AnkiWeb to make sure?
* [ X] Did you check the add-on documentation (e.g. AnkiWeb description, Wiki if it exists) for known issues?
* [X ] Did you perform a cursory search through the existing issue reports?

## What is the problem/feature you would like to see fixed/implemented?

Have anki 2.1 and am unable to get the pop up dictionary to work despite following the instructions and checking reddit. I have attached 2 images of my anki add ons and associated files

## How can we reproduce the problem?

[What were you doing when the problem occurred?]

1. [First step]
2. [Second step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]
dictionary to pop up
**Actual behavior:** [What actually happened]
Just highlights, tried double clicking and didn't work either.
**Reproducible?:** [Can you reliably reproduce the issue by following the steps above?]

## Version information

**Anki**
<img width="580" alt="ss1" src="https://user-images.githubusercontent.com/44788505/48028990-148dbd00-e11b-11e8-8413-773711042919.PNG">
<img width="518" alt="ss2" src="https://user-images.githubusercontent.com/44788505/48029078-53237780-e11b-11e8-9e34-a74f140d3352.PNG">

[Please head to *Help* → *About Anki* and Paste the version string here, e.g.:]

[Version 2.0.47]
[Qt 4.8.1 PyQt 4.9.1]

**System**

- Operating system: [Windows/macOS/Linux]
- Version: [e.g. 10, High Sierra, Ubuntu 18.04]

**Comment by glutanimate** [comment]
Thanks for the report. Some quick questions:

- Does the hotkey work? (highlight a term, then press Ctrl+Shift+D, or whatever the equivalent on macOS)
- What happens if you disable all other add-ons, restart Anki, and then try again? (Night Mode in particular is known to interfere with add-ons that modify the reviewer)

**Comment by zankidemon** [comment]
Hi,

I did some trial and error and the program only works when Night mode & Hierarchal tags are disabled

**Comment by glutanimate** [comment]
Thanks for the follow-up! OK, I'll be closing this in favor of https://github.com/krassowski/Anki-Night-Mode/issues/53 then.

(You should be fine reactivating Hierarchical Tags. There should be no interaction between the two add-ons whatsoever).
