### ISSUE TITLE
option to disable double click to evoke pop-up

### ISSUE THREAD

**Issue by omega3** [glutanimate/popup-dictionary#38]
- [x ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've checked if anyone else suggested this feature before by looking through the issue reports.

#### Problem case

I use double click on word to copy text or to check word in a dictionary, so pop-ups somehow gets in the way. 
I'd like to be able to use this add-on but to have option to switch off this behavior. A keyboard shortcut to evoke pop-up is enough for me.

**Comment by glutanimate** [comment]
Hey @omega3, thanks for the suggestion! This is definitely something I'd like to add in the future. Please feel free to follow the progress of that here: #35
