### ISSUE TITLE
Incompatible with Anki 2.1.25

### ISSUE THREAD

**Issue by Nanco300** [glutanimate/popup-dictionary#42]
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ x] I've restarted Anki to see if it helps
 - [ x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please fill out the section corresponding with your Anki version:*

##### If you are using Anki 2.1

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
    
    Anki 2.1.25 (898801eb) Python 3.8.1 Qt 5.14.1 PyQt 5.14.1
    Platform: Linux
    Flags: frz=True ao=True sv=1
    Add-ons, last update check: 2020-05-05 16:58:25
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    '' ['Free_Weekend_Load_Balancer', 0, 'None', mod]
    '' ['RequiredTags', 0, 'None', '']
    '' ['review-heatmap', 0, 'None', '']
    Advanced Browser ['874215009', 2020-04-22T19:45, 'None', '']
    Anki Simulator ['817108664', 2020-04-03T16:11, 'None', '']
    AnkiConnect ['2055492159', 2020-05-02T23:36, 'None', '']
    AwesomeTTS Google Cloud Text-to-Speech unofficial ['814349176', 2020-04-19T13:51, 'None', '']
    Batch Editing ['291119185', 2019-10-21T18:04, 'None', '']
    Blitzkrieg II - Advanced Browser Sidebar BETA8 ['564851917', 2020-04-17T00:53, 'None', '']
    Cookie monster ['1501583548', 2018-04-13T06:38, 'None', '']
    Create subs2srs cards with mpv video player ['1213145732', 2020-04-27T12:44, 'None', '']
    Enhance main window ['877182321', 2020-05-03T13:58, 'None', mod]
    Frozen Fields ['516643804', 2020-03-02T19:06, 'None', '']
    HoochieBaby Queue Controller  Day-Lrn Q ['1847358755', 2020-04-25T00:16, 'None', '']
    HoochieMama Randomize Rev Queue ['1460733408', 2020-04-25T00:16, 'None', '']
    HoochiePapa Randomize New Queue ['1173108619', 2020-04-25T00:17, 'None', '']
    Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2020-04-27T23:21, 'None', '']
    Image Style Editor ['1593969147', 2020-03-07T07:19, 'None', mod]
    Insert Randomized Lists multiple choice ['1280092568', 2019-03-16T11:44, 'None', '']
    Leaderboard ['41708974', 2020-05-02T07:11, 'None', mod]
    Mini Format Pack ['295889520', 2019-04-19T14:44, 'None', '']
    More Decks Stats and Time Left ['1556734708', 2020-03-31T17:19, 'None', mod]
    Pop-up Dictionary beta ['153625306', 2019-03-23T14:32, 'None', '']
    Progress Bar ['2091361802', 2019-04-01T13:36, 'None', '']
    Symbols ['1461102936', 2019-04-30T10:56, 'None', mod]
    True Retention ['613684242', 2019-05-08T17:15, 'None', '']
    Watch Foreign Language Movies with Anki ['939347702', 2020-05-04T11:46, 'None', '']
    Web Browser - Search terms Import texts and images automatically ['864545277', 2020-04-19T13:51, 'None', '']
    remove linebreaks  do word wrap fork for 21 ['2028179508', 2019-04-11T08:16, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1173108619 1213145732 1280092568 1374772155 1460733408 1461102936 1501583548 153625306 1556734708 1593969147 1847358755 2028179508 2055492159 2091361802 291119185 295889520 41708974 516643804 564851917 613684242 814349176 817108664 864545277 874215009 877182321 939347702
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    '' ['bettertags', 0, 'None', '']
    '' ['cloze_overlapper', 0, 'None', '']
    Card Info During Review ['2179254157', 2019-12-17T05:31, 'None', '']
    Cloze Hide All ['1709973686', 2019-12-28T09:30, 'None', '']
    DrawingPad ['370778248', 2019-11-07T09:07, 'None', '']
    ImageResizer ['1214357311', 2019-04-01T10:12, 'None', '']
    Lists to Anki Convert bulletpoint lists or Org files to Anki Cards ['1029306148', 2020-04-08T00:44, 'None', '']
    Maximum image height and width in card editor ['229181581', 2020-02-20T05:10, 'None', mod]
    More Answer Buttons with colors ['1550991760', 2019-04-08T19:24, 'None', '']
    Night Mode ['1496166067', 2020-01-29T18:27, 'None', '']
    Remaining time for Anki 21 ['1508357010', 2020-05-03T21:53, 'None', '']
    Searching PDF Reading  Note-Taking in Add Dialog ['1781298089', 2020-05-02T15:05, 'None', mod]
    Touch Screen - draw and write on your cards ['1631622775', 2019-11-07T08:37, 'None', '']
    Zoom 21 ['1846592880', 2020-01-12T14:26, 'None', '']

```

#####  If you are using Anki 2.0

*Please open Anki, go to Help → About, find the two lines starting with `Version:` and `Qt`, and copy-paste them between the backticks below:*

```
Versão 2.1.25 (898801eb)
Python 3.8.1 Qt 5.14.1 PyQt 5.14.1
```

*Please fill in details about your operating system (Windows/macOS/Linux, which version):*

- OS:Linux
- version:Ubuntu 18.04 (KDE Neon)

*Please open Anki, go to Tools → Add-ons, take a screenshot of your installed add-ons, and paste it below:*

![image](https://user-images.githubusercontent.com/34143366/81122786-3723b080-8f21-11ea-8b65-e15ed246b526.png)

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

![image](https://user-images.githubusercontent.com/34143366/81122945-8538b400-8f21-11ea-8c16-5f8e0dc9a788.png)

```python


It does not work on Anki 2.1.25, even with all other addons disabled.


```

**Comment by glutanimate** [comment]
Hi Nanco,

Thanks for the report! Just to confirm: The issue you're seeing is that, when clicking on the link to open a specific card in the browser, you get the error message above. Everything else works correctly, right? (pop-ups appear, etc.)

**Comment by Nanco300** [comment]
The error ocurs in differents cards conform gif below:
![anki-2020-05-04_19 36 39](https://user-images.githubusercontent.com/34143366/81475891-5874ed00-91fe-11ea-8164-2604458d0b9b.gif)

**Comment by glutanimate** [comment]
I just pushed a fix for this that will land in the next beta release. Thanks again for the super helpful report!

**Comment by Nanco300** [comment]
Thank 

> I just pushed a fix for this that will land in the next beta release. Thanks again for the super helpful report!

Thank you.
