### ISSUE TITLE
make the popup-dictionary require "text selection+hotkey"

### ISSUE THREAD

**Issue by ertwro** [glutanimate/popup-dictionary#51]
#### Checklist

 - [ X] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ X] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [X ] I've checked if anyone else asked this question before by looking through the issue reports.

#### Your question

How can I configure the popup_dictionary so that it only appears when I use the hotkey and not with double click?

I use a Wacom tablet due to repetitive motion injury on my wrist and I use windows ink with it. Anki recognizes any selection as double click. I want the option that it requires both "text selection + hotkey" and for that the option of disabling double click.

This was already referenced as an enhancement back in https://github.com/glutanimate/popup-dictionary/issues/38#issue-587707974 and https://github.com/glutanimate/popup-dictionary/issues/35#issue-573560545
What in the python code do I need to disable or what do I need to do?

**Comment by glutanimate** [comment]
Hey @ertwro, you should be able to manually disable the double-click handling by tweaking the logic here: https://github.com/glutanimate/popup-dictionary/blob/452011ccd94abd71356971120fdab94ccf810221/src/popup_dictionary/web/popup.js#L59-L65

For what it's worth, I've added #35 on my to-do list for the next feature release (after the current v1.0.0 stable release).
