### ISSUE TITLE
Won't Install on ⁨2.1.62 

### ISSUE THREAD

**Issue by DoctorToBeIn23** [glutanimate/popup-dictionary#81]
Version ⁨2.1.62 (bf05fae9)⁩
Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
MacBook Pro
13-inch, M1, 2020
macOS Ventura Version 13.2.1

Invalid code, or add-on not available for your version of Anki.cc

**Comment by DoctorToBeIn23** [comment]
Or on 2.1.64qt6

**Comment by glutanimate** [comment]
Hi there! A ready-made build that's compatible with recent versions of Anki (tested it recently with 2.1.65) is available [on my Patreon](https://www.patreon.com/posts/pop-up-v1-0-0-1-55381603). Alternatively you can also build the add-on from source using the latest main branch here on GitHub.
